spring.application.name=api-gateway
server.port=8080


# =====================================================
# EUREKA
# =====================================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true

eureka.client.fetch-registry=true


# =====================================================
# JWT
# =====================================================

# IMPORTANT:
# This must be the SAME secret used to create the JWT.

jwt.secret=MyVeryStrongJwtSecretKeyForPaymentGateway123456789


# =====================================================
# PAYMENT SERVICE ROUTE
# =====================================================

spring.cloud.gateway.routes[0].id=payment-service

spring.cloud.gateway.routes[0].uri=lb://payment-service

spring.cloud.gateway.routes[0].predicates[0]=Path=/payments/**


# =====================================================
# RATE LIMITER
# =====================================================

spring.cloud.gateway.routes[0].filters[0]=RequestRateLimiter

spring.cloud.gateway.routes[0].filters[0].args.key-resolver=#{@userRateLimitKeyResolver}

spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.replenishRate=1

spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.burstCapacity=2

spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.requestedTokens=1


# =====================================================
# CIRCUIT BREAKER
# =====================================================

spring.cloud.gateway.routes[0].filters[1].name=CircuitBreaker

spring.cloud.gateway.routes[0].filters[1].args.name=paymentCircuitBreaker

spring.cloud.gateway.routes[0].filters[1].args.fallbackUri=forward:/payment-fallback


# =====================================================
# TEST ROUTE
# =====================================================

spring.cloud.gateway.routes[1].id=test-service

spring.cloud.gateway.routes[1].uri=http://localhost:8081

spring.cloud.gateway.routes[1].predicates[0]=Path=/test/**


# =====================================================
# RESILIENCE4J
# =====================================================

resilience4j.circuitbreaker.instances.paymentCircuitBreaker.slidingWindowType=COUNT_BASED

resilience4j.circuitbreaker.instances.paymentCircuitBreaker.slidingWindowSize=5

resilience4j.circuitbreaker.instances.paymentCircuitBreaker.minimumNumberOfCalls=3

resilience4j.circuitbreaker.instances.paymentCircuitBreaker.failureRateThreshold=50

resilience4j.circuitbreaker.instances.paymentCircuitBreaker.waitDurationInOpenState=10s

resilience4j.circuitbreaker.instances.paymentCircuitBreaker.permittedNumberOfCallsInHalfOpenState=2

resilience4j.circuitbreaker.instances.paymentCircuitBreaker.automaticTransitionFromOpenToHalfOpenEnabled=true


# =====================================================
# REDIS
# =====================================================

spring.data.redis.host=localhost

spring.data.redis.port=6379


# =====================================================
# ACTUATOR
# =====================================================

management.endpoints.web.exposure.include=health,info,metrics,mappings

management.endpoint.health.show-details=always


