apiVersion: v1
kind: Secret

metadata:
  name: api-gateway-secret
  namespace: investra

type: Opaque

stringData:

  # JWT
  JWT_SECRET: "YOUR_JWT_SECRET"

  # Internal Kubernetes services
  AUTH_SERVICE_URL: "https://auth-service-16u2.onrender.com"
  FUND_SERVICE_URL: "https://fund-service-5x7p.onrender.com"
  ORDER_SERVICE_URL: "https://order-service-eahf.onrender.com"
  PAYMENT_SERVICE_URL: "https://payment-service-xo3a.onrender.com"
  OTP_SERVICE_URL: "https://otp-service-q21n.onrender.com"

  # Redis
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"

  # React frontend
  FRONTEND_URL: "https://fund-service-5x7p.onrender.com"