apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-gateway
  namespace: investra

spec:

  replicas: 2

  selector:
    matchLabels:
      app: api-gateway

  template:

    metadata:
      labels:
        app: api-gateway

    spec:

      containers:

        - name: api-gateway

          image: api-gateway:local

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080

          envFrom:
            - secretRef:
                name: api-gateway-secret

          resources:

            requests:
              cpu: 100m
              memory: 512Mi

            limits:
              cpu: 500m
              memory: 768Mi

          # Gateway has Spring Boot Actuator

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5